apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fetcher-worker.fullname" . }}
  labels:
    {{- include "fetcher-worker.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.worker.configmap }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if .Values.worker.image.tag }}
  VERSION: {{ .Values.worker.image.tag | quote }}
  {{- else }}
  VERSION: {{ .Chart.AppVersion | quote }}
  {{- end }}
  {{- with .Values.worker.extraEnvVars }}
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
