{{- if not .Values.worker.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fetcher-worker.fullname" . }}
  labels:
    {{- include "fetcher-worker.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.worker.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
