apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fetcher.fullname" . }}-common
  labels:
    {{- include "fetcher.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.common.configmap }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
