apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fetcher.fullname" . }}-common
  labels:
    {{- include "fetcher.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
