onboarding:
  - changed-files:
      - any-glob-to-any-file: charts/midaz/templates/onboarding/**

trasaction:
  - changed-files:
      - any-glob-to-any-file: charts/midaz/templates/trasaction/**

console:
  - changed-files:
      - any-glob-to-any-file: charts/midaz/templates/console/**

audit:
  - changed-files:
      - any-glob-to-any-file: charts/midaz/templates/audit/**

auth:
  - changed-files:
      - any-glob-to-any-file: charts/midaz/**

dependencies:
  - changed-files:
      - any-glob-to-any-file: charts/midaz/**

values:
  - changed-files:
      - any-glob-to-any-file: charts/midaz/**

pipe:
  - changed-files:
      - any-glob-to-any-file: .github/workflows/**

doc:
  - changed-files:
      - any-glob-to-any-file: README.md
