midaz:
  - changed-files:
      - any-glob-to-any-file: charts/midaz/**

otel-collector:
  - changed-files:
      - any-glob-to-any-file: charts/otel-collector-lerian/**

plugin-access-manager:
  - changed-files:
      - any-glob-to-any-file: charts/plugin-access-manager/**

reporter:
  - changed-files:
      - any-glob-to-any-file: charts/reporter/**

plugin-crm:
  - changed-files:
      - any-glob-to-any-file: charts/plugin-crm/**

plugin-fees:
  - changed-files:
      - any-glob-to-any-file: charts/plugin-fees/**

plugin-br-pix-indirect-btg:
  - changed-files:
      - any-glob-to-any-file: charts/plugin-br-pix-indirect-btg/**

plugin-br-pix-direct-jd:
  - changed-files:
      - any-glob-to-any-file: charts/plugin-br-pix-direct-jd/**
      
product-console:
  - changed-files:
      - any-glob-to-any-file: charts/product-console/**

fetcher:
  - changed-files:
      - any-glob-to-any-file: charts/fetcher/**

matcher:
  - changed-files:
      - any-glob-to-any-file: charts/matcher/**

pipe:
  - changed-files:
      - any-glob-to-any-file: .github/workflows/**

doc:
  - changed-files:
      - any-glob-to-any-file: README.md

flowker:
  - changed-files:
      - any-glob-to-any-file: charts/flowker/**