midaz:
  - changed-files:
      - any-glob-to-any-file: charts/midaz/**

plugin-access-manager:
  - changed-files:
      - any-glob-to-any-file: charts/plugin-access-manager/**

plugin-smart-templates:
  - changed-files:
      - any-glob-to-any-file: charts/plugin-smart-templates/**

plugin-crm:
  - changed-files:
      - any-glob-to-any-file: charts/plugin-crm/**

plugin-fees:
  - changed-files:
      - any-glob-to-any-file: charts/plugin-fees/**

pipe:
  - changed-files:
      - any-glob-to-any-file: .github/workflows/**

doc:
  - changed-files:
      - any-glob-to-any-file: README.md