apiVersion: v2
name: matcher-helm
description: A Helm chart for the Matcher reconciliation service

type: application

home: https://github.com/LerianStudio/midaz-helm

sources:
  - https://github.com/LerianStudio/midaz-helm/tree/main/charts/matcher
  - https://github.com/LerianStudio/matcher

maintainers:
  - name: "Lerian Studio"
    email: "support@lerian.studio"

version: 1.1.0

appVersion: "1.0.0"

keywords:
  - matcher
  - reconciliation
  - lerian
  - ledger
  - transactions

icon: https://avatars.githubusercontent.com/u/148895005?s=200&v=4

dependencies:
  - name: valkey
    version: "2.4.7"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: valkey.enabled
  - name: postgresql
    version: "16.3"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: rabbitmq
    version: "2.1.11"
    repository: "https://groundhog2k.github.io/helm-charts"
    condition: rabbitmq.enabled
