{{- if .Values.reconciliation.autoscaling.enabled }}
{{- if not (or .Values.reconciliation.autoscaling.targetCPUUtilizationPercentage .Values.reconciliation.autoscaling.targetMemoryUtilizationPercentage) }}
{{- fail "At least one of targetCPUUtilizationPercentage or targetMemoryUtilizationPercentage must be set when autoscaling is enabled" }}
{{- end }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "reconciliation.fullname" . }}
  labels:
    {{- include "reconciliation.labels" (dict "context" . "name" .Values.reconciliation.name ) | nindent 4 }} 
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "reconciliation.fullname" . }}
  minReplicas: {{ .Values.reconciliation.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.reconciliation.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.reconciliation.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.reconciliation.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.reconciliation.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.reconciliation.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}