apiVersion: v1
kind: Service
metadata:
  name: {{ include "reconciliation.fullname" . }}
  labels:
    {{- include "reconciliation.labels" (dict "context" . "name" .Values.reconciliation.name ) | nindent 4 }} 
spec:
  type: {{ .Values.reconciliation.service.type }}
  ports:
    - port: {{ .Values.reconciliation.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "reconciliation.selectorLabels" (dict "context" . "name" .Values.reconciliation.name) | nindent 4 }}