apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "product-console.fullname" . }}
  labels:
    {{- include "product-console.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configmap }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if .Values.image.tag }}
  VERSION: {{ .Values.image.tag | quote }}
  {{- else }}
  VERSION: {{ .Chart.AppVersion | quote }}
  {{- end }}
  {{- with .Values.extraEnvVars }}
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
