{{- if not .Values.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "product-console.fullname" . }}
  labels:
    {{- include "product-console.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
