apiVersion: v2
name: reporter-helm
description: A Helm chart for deploying Golang applications
type: application

home: https://github.com/LerianStudio/reporter/tree/main/deploy/charts/reporter
sources:
  - https://github.com/LerianStudio/reporter/tree/main/deploy/charts/reporter
  - https://github.com/LerianStudio/reporter

# A list of maintainers who are responsible for the chart
maintainers:
  - name: "Lerian Studio"
    email: "support@lerian.studio"

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.

version: 1.1.4-beta.2

# This is the version number of the application being deployed.
appVersion: "4.0.0"

# A list of keywords about the chart. This helps others discover the chart.
keywords:
  - midaz
  - lerian
  - ledger
  - reporter

# The URL to an icon file for this chart. Or the icon data.
icon: https://avatars.githubusercontent.com/u/148895005?s=200&v=4

# Dependencies
dependencies:
  - name: keda
    version: "2.17.1"
    repository: "https://kedacore.github.io/charts"
    condition: keda.enabled
    tags:
      - keda-operator
  - name: seaweedfs
    version: "4.0.393"
    repository: "https://seaweedfs.github.io/seaweedfs/helm"
    condition: seaweedfs.enabled
  - name: mongodb
    version: "16.4.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mongodb.enabled
  - name: rabbitmq
    version: "2.1.11"
    repository: "https://groundhog2k.github.io/helm-charts"
    condition: rabbitmq.enabled
  - name: valkey
    version: "0.7.4"
    repository: "https://valkey.io/valkey-helm"
    condition: valkey.enabled
