apiVersion: v1
kind: Service
metadata:
  name: {{ include "midaz-ledger.fullname" . }}
  labels:
    {{- include "midaz.labels" (dict "context" . "component" .Values.ledger.name "name" .Values.ledger.name ) | nindent 4 }}
spec:
  type: {{ .Values.ledger.service.type }}
  ports:
    - port: {{ .Values.ledger.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "midaz.selectorLabels" (dict "context" . "name" .Values.ledger.name) | nindent 4 }}