apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "plugin-worker.fullname" . }}
  labels:
    {{- include "plugin-worker.labels" (dict "context" . "name" .Values.worker.name ) | nindent 4 }}
  {{- with .Values.worker.configmap.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }} 
data:
  # Common shared values
  {{- range $key, $value := .Values.common.configmap }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  # Worker specific values
  {{- range $key, $value := .Values.worker.configmap }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  # Extra Env Vars
  {{- with .Values.worker.extraEnvVars }}
  {{- toYaml . | nindent 2 }}
  {{- end }}