apiVersion: v2
name: flowker-helm
description: A Helm chart for Flowker - Workflow orchestration platform for
  financial validation
type: application
home: https://github.com/LerianStudio/flowker
sources:
  - https://github.com/LerianStudio/flowker
maintainers:
  - name: "Lerian Studio"
    email: "support@lerian.studio"
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - flowker
  - workflow
  - orchestration
  - financial-validation
  - lerian
icon: https://avatars.githubusercontent.com/u/148895005?s=200&v=4
dependencies:
  - name: mongodb
    version: "16.4.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mongodb.enabled
