apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fetcher-manager.fullname" . }}
  labels:
    {{- include "fetcher-manager.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.manager.configmap }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if .Values.manager.image.tag }}
  VERSION: {{ .Values.manager.image.tag | quote }}
  {{- else }}
  VERSION: {{ .Chart.AppVersion | quote }}
  {{- end }}
  {{- with .Values.manager.extraEnvVars }}
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
