{{- if .Values.manager.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fetcher-manager.serviceAccountName" . }}
  labels:
    {{- include "fetcher-manager.labels" . | nindent 4 }}
  {{- with .Values.manager.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
