apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "midaz-audit.fullname" . }}
  labels:
    {{- include "midaz.labels" (dict "context" . "component" .Values.audit.name "name" .Values.audit.name ) | nindent 4 }}
spec:
  {{- if not .Values.audit.autoscaling.enabled }}
  replicas: {{ .Values.audit.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "midaz.selectorLabels" (dict "context" . "name" .Values.audit.name ) | nindent 6 }}
  template:
    metadata:
      {{- with .Values.audit.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "midaz.labels" (dict "context" . "component" .Values.audit.name "name" .Values.audit.name ) | nindent 8 }}
    spec:
      {{- with .Values.audit.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.audit.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.audit.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "midaz-audit.fullname" . }}
          securityContext:
            {{- toYaml .Values.audit.securityContext | nindent 12 }}
          image: "{{ .Values.audit.image.repository }}:{{ .Values.audit.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.audit.image.pullPolicy }}
          envFrom:
          - secretRef:
              name: {{ include "midaz-audit.fullname" . }}
          - configMapRef:
              name: {{ include "midaz-audit.fullname" . }}
          ports:
            - name: http
              containerPort: 3005
              protocol: TCP
          resources:
            {{- toYaml .Values.audit.resources | nindent 12 }}
        - name: {{ include "midaz-audit.fullname" . }}{{ "-server" }}
          image: gcr.io/trillian-opensource-ci/log_server
          imagePullPolicy: IfNotPresent
          args: 
            - "--storage_system=mysql"
            - "--mysql_uri=$(TRILLIAN_DATABASE_USER):$(TRILLIAN_DATABASE_PASSWORD)@tcp($(TRILLIAN_DATABASE_HOST):$(TRILLIAN_DATABASE_PORT))/$(TRILLIAN_DATABASE_NAME)"
            - "--rpc_endpoint=0.0.0.0:$(TRILLIAN_GRPC_PORT)"
            - "--http_endpoint=0.0.0.0:$(TRILLIAN_HTTP_PORT)"
            - "--alsologtostderr"
          env:
            - name: TRILLIAN_DATABASE_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "midaz-audit.fullname" . }}
                  key: TRILLIAN_DATABASE_USER
            - name: TRILLIAN_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "midaz-audit.fullname" . }}
                  key: TRILLIAN_DATABASE_PASSWORD
            - name: TRILLIAN_DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "midaz-audit.fullname" . }}
                  key: TRILLIAN_DATABASE_PORT
            - name: TRILLIAN_DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "midaz-audit.fullname" . }}
                  key: TRILLIAN_DATABASE_NAME
            - name: TRILLIAN_GRPC_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "midaz-audit.fullname" . }}
                  key: TRILLIAN_GRPC_PORT
            - name: TRILLIAN_HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "midaz-audit.fullname" . }}
                  key: TRILLIAN_HTTP_PORT
            - name: TRILLIAN_DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "midaz-audit.fullname" . }}
                  key: TRILLIAN_DATABASE_HOST
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8091
            failureThreshold: 3
            periodSeconds: 30
            timeoutSeconds: 5
          ports:
            - name: rpc
              containerPort: 8090
            - name: metrics
              containerPort: 8091
          resources:
            {{- toYaml .Values.audit.server.resources | nindent 12 }}
        - name: {{ include "midaz-audit.fullname" . }}{{ "-signer" }}
          image: gcr.io/trillian-opensource-ci/log_signer
          imagePullPolicy: IfNotPresent
          args: 
            - "--storage_system=mysql"
            - "--mysql_uri=$(TRILLIAN_DATABASE_USER):$(TRILLIAN_DATABASE_PASSWORD)@tcp($(TRILLIAN_DATABASE_HOST):$(TRILLIAN_DATABASE_PORT))/$(TRILLIAN_DATABASE_NAME)"
            - "--rpc_endpoint=0.0.0.0:$(TRILLIAN_SIGNER_GRPC_PORT)"
            - "--http_endpoint=0.0.0.0:$(TRILLIAN_SIGNER_HTTP_PORT)"
            - "--force_master"
            - "--alsologtostderr"
          env:
            - name: TRILLIAN_DATABASE_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "midaz-audit.fullname" . }}
                  key: TRILLIAN_DATABASE_USER
            - name: TRILLIAN_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "midaz-audit.fullname" . }}
                  key: TRILLIAN_DATABASE_PASSWORD
            - name: TRILLIAN_DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "midaz-audit.fullname" . }}
                  key: TRILLIAN_DATABASE_PORT
            - name: TRILLIAN_DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "midaz-audit.fullname" . }}
                  key: TRILLIAN_DATABASE_NAME
            - name: TRILLIAN_SIGNER_GRPC_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "midaz-audit.fullname" . }}
                  key: TRILLIAN_SIGNER_GRPC_PORT
            - name: TRILLIAN_SIGNER_HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "midaz-audit.fullname" . }}
                  key: TRILLIAN_SIGNER_HTTP_PORT
            - name: TRILLIAN_DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "midaz-audit.fullname" . }}
                  key: TRILLIAN_DATABASE_HOST
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8092
            failureThreshold: 3
            periodSeconds: 30
            timeoutSeconds: 5
          ports:
            - name: http-signer
              containerPort: 8092
            - name: rpc-signer
              containerPort: 8093
          resources:
            {{- toYaml .Values.audit.signer.resources | nindent 12 }}
      {{- with .Values.audit.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.audit.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.audit.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}