{{- if and .Values.flowker.enabled (not .Values.flowker.useExistingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flowker.fullname" . }}
  namespace: {{ include "global.namespace" . }}
  labels:
    {{- include "flowker.labels" (dict "context" . "component" .Values.flowker.name "name" .Values.flowker.name) | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.flowker.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
