{{- if and .Values.flowker.enabled .Values.flowker.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "flowker.serviceAccountName" . }}
  namespace: {{ include "global.namespace" . }}
  labels:
    {{- include "flowker.labels" (dict "context" . "component" .Values.flowker.name "name" .Values.flowker.name) | nindent 4 }}
  {{- with .Values.flowker.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
