apiVersion: v2
name: product-console-helm
description: A Helm chart for Product Console - Lerian Studio's web interface for managing Midaz ledger
type: application

home: https://github.com/LerianStudio/helm

sources:
  - https://github.com/LerianStudio/helm/tree/main/charts/product-console
  - https://github.com/LerianStudio/product-console

# A list of maintainers who are responsible for the chart
maintainers:
  - name: "Lerian Studio"
    email: "support@lerian.studio"

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 1.0.0

# This is the version number of the application being deployed.
appVersion: "1.0.0"

# A list of keywords about the chart. This helps others discover the chart.
keywords:
  - midaz
  - lerian
  - ledger
  - console
  - web-ui

# The URL to an icon file for this chart. Or the icon data.
icon: https://avatars.githubusercontent.com/u/148895005?s=200&v=4
