apiVersion: v2
name: midaz-helm-standalone
description: A Helm chart for Kubernetes
type: application

home: https://github.com/LerianStudio/midaz-helm-standalone

sources:
  - https://github.com/LerianStudio/midaz-helm-standalone/tree/main/charts/midaz
  - https://github.com/LerianStudio/midaz

# A list of maintainers who are responsible for the chart
maintainers:
  - name: "Lerian Studio"
    email: "support@lerian.studio"

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 1.49.2

# This is the version number of the application being deployed. 
appVersion: "1.49.2"

# A list of keywords about the chart. This helps others discover the chart.
keywords:
  - midaz
  - lerian
  - ledger

# The URL to an icon file for this chart. Or the icon data.
icon: https://avatars.githubusercontent.com/u/148895005?s=200&v=4

# This Helm chart includes multiple dependencies required for the application. 
# To understand the purpose and configuration of each dependency, visit:
# https://docs.lerian.studio/docs/midaz-components  
dependencies:
  - name: redis
    version: "19.3"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: postgresql
    version: "16.3"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: postgresql
    alias: casdoordb
    version: "16.3"
    repository: "https://charts.bitnami.com/bitnami"
    condition: casdoordb.enabled
  - name: mongodb
    version: "16.4.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mongodb.enabled
  - name: rabbitmq
    version: "15.2"
    repository: "https://charts.bitnami.com/bitnami"
    condition: rabbitmq.enabled
  - name: casdoor-helm-charts
    alias: casdoor
    version: "v1.835.0"
    repository: "oci://registry-1.docker.io/casbin"
    condition: casdoor.enabled
  - name: mariadb
    version: "20.2"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mariadb.enabled
