apiVersion: v2
name: midaz-helm-standalone
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "1.46.0"

dependencies:
  - name: redis
    version: "19.3"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: postgresql
    version: "16.3"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: postgresql
    alias: casdoordb
    version: "16.3"
    repository: "https://charts.bitnami.com/bitnami"
    condition: casdoordb.enabled
  - name: mongodb
    version: "16.4.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mongodb.enabled
  - name: rabbitmq
    version: "15.2"
    repository: "https://charts.bitnami.com/bitnami"
    condition: rabbitmq.enabled
  - name: casdoor-helm-charts
    alias: casdoor
    version: "v1.799.0"
    repository: "oci://registry-1.docker.io/casbin"
    condition: casdoor.enabled
  - name: mariadb
    version: "20.2"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mariadb.enabled
