apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fetcher-helm.fullname" . }}-fetcher-worker
  labels:
    {{- include "fetcher-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: fetcher-worker
type: Opaque
data:
  REDIS_PASSWORD: {{ .Values.worker.secrets.REDIS_PASSWORD | default "CHANGE_ME_set_secure_password" | b64enc | quote }}
  # Extra Secret Vars
  {{- if .Values.worker.extraSecretVars }}
  {{- toYaml .Values.worker.extraSecretVars | nindent 2 }}
  {{- end }}
