apiVersion: v2
name: fetcher-helm
description: A Helm chart for Fetcher - Data extraction service for Lerian Studio

type: application

home: https://github.com/LerianStudio/fetcher

maintainers:
  - name: "Lerian Studio"
    email: "support@lerian.studio"

version: 1.1.0
appVersion: "1.0.0"

keywords:
  - midaz
  - lerian
  - fetcher
  - data-extraction

icon: https://avatars.githubusercontent.com/u/148895005?s=200&v=4

# Dependencies
dependencies:
  - name: keda
    version: "2.17.1"
    repository: "https://kedacore.github.io/charts"
    condition: keda.enabled
    tags:
      - keda-operator
  - name: seaweedfs
    version: "4.0.393"
    repository: "https://seaweedfs.github.io/seaweedfs/helm"
    condition: seaweedfs.enabled
  - name: mongodb
    version: "16.4.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mongodb.enabled
  - name: rabbitmq
    version: "2.1.11"
    repository: "https://groundhog2k.github.io/helm-charts"
    condition: rabbitmq.enabled
  - name: valkey
    version: "0.7.4"
    repository: "https://valkey.io/valkey-helm"
    condition: valkey.enabled
