apiVersion: v2
name: plugin-br-pix-indirect-btg-helm
description: A Helm chart for Kubernetes
type: application

home: https://github.com/LerianStudio/helm

# A list of maintainers who are responsible for the chart
maintainers:
  - name: "Lerian Studio"
    email: "support@lerian.studio"

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 1.0.0-beta.7

# This is the version number of the application being deployed.
appVersion: "1.0.0-rc.27"

# A list of keywords about the chart. This helps others discover the chart.
keywords:
  - midaz
  - lerian
  - ledger
  - plugins
  - pix

# The URL to an icon file for this chart. Or the icon data.
icon: https://avatars.githubusercontent.com/u/148895005?s=200&v=4

dependencies:
  - name: postgresql
    version: "16.3"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: valkey
    version: "0.7.4"
    repository: "https://valkey.io/valkey-helm"
    condition: valkey.enabled
  - name: mongodb
    version: "16.4.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mongodb.enabled
