{{- if and .Values.tracer.enabled (not .Values.tracer.useExistingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tracer.fullname" . }}
  namespace: {{ include "global.namespace" . }}
  labels:
    {{- include "tracer.labels" (dict "context" . "component" .Values.tracer.name "name" .Values.tracer.name) | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.tracer.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
