{{- if and .Values.tracer.enabled .Values.tracer.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tracer.serviceAccountName" . }}
  namespace: {{ include "global.namespace" . }}
  labels:
    {{- include "tracer.labels" (dict "context" . "component" .Values.tracer.name "name" .Values.tracer.name) | nindent 4 }}
  {{- with .Values.tracer.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
