{{- if .Values.inbound.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "inbound.fullname" . }}
  labels:
    {{- include "inbound.labels" (dict "context" . "name" .Values.inbound.name ) | nindent 4 }} 
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "inbound.fullname" . }}
  minReplicas: {{ .Values.inbound.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.inbound.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.inbound.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.inbound.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.inbound.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.inbound.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}