apiVersion: v1
kind: Service
metadata:
  name: {{ include "inbound.fullname" . }}
  labels:
    {{- include "inbound.labels" (dict "context" . "name" .Values.inbound.name ) | nindent 4 }} 
spec:
  type: {{ .Values.inbound.service.type }}
  ports:
    - port: {{ .Values.inbound.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "inbound.selectorLabels" (dict "context" . "name" .Values.inbound.name) | nindent 4 }}