{{- if not .Values.outbound.useExistingSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "outbound.fullname" . }}
  labels:
    {{- include "outbound.labels" (dict "context" . "name" .Values.outbound.name ) | nindent 4 }}
  annotations:
    # Vault KV v2
    avp.kubernetes.io/kv-version: "2"
    # Opcional: define o path uma vez só (aí usamos <path:#KEY> nos campos)
    avp.kubernetes.io/path: secret/data/firmino/plugin-br-pix-indirect-btg
type: Opaque
data:
  # -- Default sensitive variables for the plugin-br-pix-indirect-btg

  # DB Configuration
  DB_REPLICA_PASSWORD: {{ .Values.outbound.secrets.DB_REPLICA_PASSWORD | default "" | b64enc | quote }}
  DB_PASSWORD: {{ .Values.outbound.secrets.DB_PASSWORD | default "" | b64enc | quote }}

  # MongoDB Configuration
  MONGO_PASSWORD: {{ .Values.outbound.secrets.MONGO_PASSWORD | default "" | b64enc | quote }}

{{- end }}
