{{- if not .Values.outbound.useExistingSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "outbound.fullname" . }}
  labels:
    {{- include "outbound.labels" (dict "context" . "name" .Values.outbound.name ) | nindent 4 }}
type: Opaque
data:
  # -- Default sensitive variables for the plugin-br-pix-indirect-btg

  # DB Configuration
  DB_REPLICA_PASSWORD: {{ .Values.outbound.secrets.DB_REPLICA_PASSWORD | default "" | b64enc | quote }}
  DB_PASSWORD: {{ .Values.outbound.secrets.DB_PASSWORD | default "" | b64enc | quote }}

  # MongoDB Configuration
  MONGO_PASSWORD: {{ .Values.outbound.secrets.MONGO_PASSWORD | default "" | b64enc | quote }}

{{- end }}
