kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "midaz-ledger.fullname" . }}
data:
  ENV_NAME: local
  SERVER_PORT: 3000
  SERVER_ADDRESS: 3000
  MONGO_HOST: mongo-mongodb.midaz.svc.cluster.local
  MONGO_NAME: ledger
  MONGO_USER: midaz
  MONGO_PORT: 27017
  REDIS_HOST: redis-headless.midaz.svc.cluster.local
  REDIS_PORT: 6379
  DB_HOST: postgres-postgresql.midaz.svc.cluster.local
  DB_USER: midaz
  DB_NAME: ledger
  DB_PORT: 5432
  DB_REPLICA_HOST: postgres-postgresql.midaz.svc.cluster.local
  DB_REPLICA_USER: midaz
  DB_REPLICA_NAME: ledger
  DB_REPLICA_PORT: 5432
  REPLICATION_USER: replicator
  USER_EXECUTE_COMMAND: postgres
  LOG_LEVEL: debug
  MONGO_PASSWORD: lerian
  DB_PASSWORD: lerian
  DB_REPLICA_PASSWORD: lerian
  REPLICATION_PASSWORD: lerian
