{{- if .Values.karpenter.enabled }}
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: {{ include "midaz-ledger.fullname" . }}
spec:
  template:
    metadata:
      labels:
        type: {{ include "midaz-ledger.fullname" . }}
      annotations:
        midaz.io/owner: {{ include "midaz-ledger.fullname" . }}
    spec:
      startupTaints:
        - key: ebs.csi.aws.com/agent-not-ready
          effect: NoExecute
      taints:
        - key: midaz.io/midaz
          effect: NoSchedule
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: "node.kubernetes.io/instance-type"
          operator: In
          values:
          {{- with .Values.karpenter.instance_types }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      nodeClassRef:
        name: {{ include "midaz-ledger.fullname" . }}
  limits:
    cpu: 1000
    memory: 2000Gi
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h
---

apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: {{ include "midaz-ledger.fullname" . }}
spec:
  amiFamily: AL2
  role: {{ .Values.karpenter.cluster.iam_role_name }}
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.karpenter.cluster.name }}
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.karpenter.cluster.name }}
  tags:
    Name: {{ include "midaz-ledger.fullname" . }}
    Manager: "karpenter"
{{- end }}