{{- if .Values.matcher.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "matcher.fullname" . }}
  namespace: {{ include "global.namespace" . }}
  labels:
    {{- include "matcher.labels" (dict "context" . "component" .Values.matcher.name "name" .Values.matcher.name ) | nindent 4 }}
  {{- with .Values.matcher.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.matcher.service.type }}
  ports:
    - port: {{ .Values.matcher.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "matcher.selectorLabels" (dict "context" . "name" .Values.matcher.name) | nindent 4 }}
{{- end }}
