{{- if and .Values.matcher.enabled .Values.matcher.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "matcher.serviceAccountName" . }}
  namespace: {{ include "global.namespace" . }}
  labels:
    {{- include "matcher.labels" (dict "context" . "component" .Values.matcher.name "name" .Values.matcher.name ) | nindent 4 }}
  {{- with .Values.matcher.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
