{{- if .Values.crm.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "midaz-crm.fullname" . }}
  labels:
    {{- include "midaz-crm.labels" (dict "context" . "name" .Values.crm.name ) | nindent 4 }}
spec:
  revisionHistoryLimit: {{ .Values.crm.revisionHistoryLimit | default 10 }}
  strategy:
    type: {{ .Values.crm.deploymentUpdate.type }}
    {{- if eq .Values.crm.deploymentUpdate.type "RollingUpdate" }}
    rollingUpdate:
      maxSurge: {{ .Values.crm.deploymentUpdate.maxSurge }}
      maxUnavailable: {{ .Values.crm.deploymentUpdate.maxUnavailable }}
    {{- end }}
  {{- if not .Values.crm.autoscaling.enabled }}
  replicas: {{ .Values.crm.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "midaz-crm.selectorLabels" (dict "context" . "name" .Values.crm.name) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "midaz-crm.labels" (dict "context" . "name" .Values.crm.name ) | nindent 8 }}
      {{- with .Values.crm.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
    {{- with .Values.crm.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      {{- with .Values.crm.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "midaz-crm.fullname" . }}
          image: {{ .Values.crm.image.repository }}:{{ .Values.crm.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.crm.image.pullPolicy }}
          {{- with .Values.crm.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.crm.service.port }}
              protocol: TCP
          envFrom:
          {{- if not .Values.crm.useExistingSecret }}
          - secretRef:
              name: {{ include "midaz-crm.fullname" . }}
          {{- else }}
          - secretRef:
              name: {{ .Values.crm.existingSecretName }}
          {{- end }}
          - configMapRef:
              name: {{ include "midaz-crm.fullname" . }}
          {{- if or (index .Values "otel-collector-lerian").enabled (index .Values "otel-collector-lerian").external }}
          env:
          - name: "HOST_IP"
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: "OTEL_EXPORTER_OTLP_ENDPOINT"
            value: "$(HOST_IP):4317"
          {{- end }}
          resources:
            {{- toYaml .Values.crm.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.crm.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /health
              port: {{ .Values.crm.service.port }}
      {{- with .Values.crm.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.crm.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.crm.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
