{{- if and .Values.crm.enabled .Values.crm.autoscaling.enabled (or .Values.crm.autoscaling.targetCPUUtilizationPercentage .Values.crm.autoscaling.targetMemoryUtilizationPercentage) }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "midaz-crm.fullname" . }}
  labels:
    {{- include "midaz-crm.labels" (dict "context" . "name" .Values.crm.name ) | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "midaz-crm.fullname" . }}
  minReplicas: {{ .Values.crm.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.crm.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.crm.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.crm.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.crm.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.crm.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
