apiVersion: v2
name: tracer-helm
description: A Helm chart for Tracer - Real-time transaction validation and
  fraud prevention API

type: application

home: https://github.com/LerianStudio/midaz-helm

sources:
  - https://github.com/LerianStudio/midaz-helm/tree/main/charts/tracer
  - https://github.com/LerianStudio/tracer

maintainers:
  - name: "Lerian Studio"
    email: "support@lerian.studio"

version: 1.0.0-beta.1

appVersion: "1.0.0"

keywords:
  - tracer
  - fraud-prevention
  - transaction-validation
  - lerian
  - ledger

icon: https://avatars.githubusercontent.com/u/148895005?s=200&v=4
