apiVersion: v2
name: underwriter-helm
description: A Helm chart for Underwriter - Risk assessment and underwriting
  service for Lerian Studio

type: application

home: https://github.com/LerianStudio/underwriter

sources:
  - https://github.com/LerianStudio/midaz-helm/tree/main/charts/underwriter
  - https://github.com/LerianStudio/underwriter

maintainers:
  - name: "Lerian Studio"
    email: "support@lerian.studio"

version: 1.0.0-beta.1

appVersion: "1.0.0"

keywords:
  - underwriter
  - risk-assessment
  - lerian
  - ledger

icon: https://avatars.githubusercontent.com/u/148895005?s=200&v=4

dependencies:
  - name: valkey
    version: "2.4.7"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: valkey.enabled
  - name: postgresql
    version: "16.3"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
