{{- if and .Values.underwriter.enabled .Values.underwriter.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "underwriter.fullname" . }}
  namespace: {{ include "global.namespace" . }}
  labels:
    {{- include "underwriter.labels" (dict "context" . "component" .Values.underwriter.name "name" .Values.underwriter.name) | nindent 4 }}
  {{- with .Values.underwriter.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.underwriter.ingress.className }}
  ingressClassName: {{ .Values.underwriter.ingress.className }}
  {{- end }}
  {{- if .Values.underwriter.ingress.tls }}
  tls:
    {{- range .Values.underwriter.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.underwriter.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "underwriter.fullname" $ }}
                port:
                  number: {{ $.Values.underwriter.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
