{{- if and .Values.underwriter.enabled (not .Values.underwriter.useExistingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "underwriter.fullname" . }}
  namespace: {{ include "global.namespace" . }}
  labels:
    {{- include "underwriter.labels" (dict "context" . "component" .Values.underwriter.name "name" .Values.underwriter.name) | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.underwriter.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
