{{- if or .Values.keda.enabled .Values.keda.external }}
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-authentication
  labels:
    {{- include "plugin-manager.labels" (dict "context" . "name" .Values.manager.name ) | nindent 4 }}
spec:
  secretTargetRef:
    - parameter: username
      name: {{ .Values.keda.triggerAuthentication.secretName | default (include "plugin-manager.fullname" .) }}
      key: {{ .Values.keda.triggerAuthentication.usernameKey | default "RABBITMQ_DEFAULT_USER" }}
    - parameter: password
      name: {{ .Values.keda.triggerAuthentication.secretName | default (include "plugin-manager.fullname" .) }}
      key: {{ .Values.keda.triggerAuthentication.passwordKey | default "RABBITMQ_DEFAULT_PASS" }}
{{- end }}